### ISSUE TITLE
Being able to manage Iterations

### ISSUE THREAD

**Issue by devpro** [Azure/azure-devops-cli-extension#128]
With Visual Studio Team Services CLI 0.1.0b0, it's not possible to create an Iteration.
It would save a lot of time to be able to do it from the command line, potentially with a generator, for example: generate for me 10 iterations starting next Monday.

**Comment by Crashdummyy** [comment]
Any Progress so far?

**Comment by geverghe** [comment]
@caderoux , @Crashdummyy, @devpro - quick question - the scenario is that you want to create iterations for a particular team? project? or both?

**Comment by devpro** [comment]
Hello @geverghe, both would be nice but at least for one team would be great. This is not the most interesting thing to do :)

**Comment by geverghe** [comment]
Got it, thanks! 👍

**Comment by geverghe** [comment]
@caderoux , @devpro , @Crashdummyy : Here are the commands that we are building to manage iterations:

# Commands
## Create an iteration
`az boards iteration project create`
`az boards iteration team create`

## List iterations
`az boards iteration project list`
`az boards iteration team list`

## Show
`az boards iteration project show`
`az boards iteration team show`

## Update
`az boards iteration project update`
`az boards iteration team update`

## Delete/Remove
`az boards iteration project delete`
`az boards iteration team delete`

## List work items pertaining to an iteration
`az boards iteration team list-work-item`

# Important Decision Points
1. Why is it `iteration team/project` rather than `team\project iteration`?
Only iteration and areas have a team/project scope. Remaining board configs have only team as the setting container. Further, even in the iteration commands listed, iteration is the top group pertaining to which the verb action is being taken with project and team being just application scopes. Therefore, team/project become the sub group to host the command set.
2. Shouldn't `project/team` be just switches for the iteration command rather than sub groups?
Today boards iteration set up for teams and project are different, implemented by two different APIs. Therefore, all the actions available for iterations in team are not available for iterations in project. The thought was that from a user experience point of view, it becomes challenging to set up that expectation with just a parameter switch and hence the command sub group.
3. What is the reason for verb difference in `iteration team remove` and `iteration project delete`?
Iteration remove from teams does not delete the iteration but just removes it from the team back log. Therefore, remove seemed to be a more apt verb rather than delete. Delete in iteration project actually deletes an iteration

**Comment by geverghe** [comment]
Closing this ticket as iteration and area commands are now available in the latest version - [0.11.0 Release](https://github.com/Azure/azure-devops-cli-extension/releases/tag/20190619.2)
