### ISSUE TITLE
Enhancement - work item query - load wiql from file

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-devops-cli-extension#210]
Allowing users to load wiql from files would simplify the usage.

**Comment by gauravsaralMs** [comment]
@clarkbreyman-yammer : we have a command which take WIQL in param
`az boards query --org https://gsaralprivate.visualstudio.com -p 210 --wiql "SELECT [System.Id] from workitems where [System.Title] = 'Bug 1'"`

Just curious about the scenario you are trying to solve and can you pass WIQL from parameter instead of passing it through file?

**Comment by gauravsaralMs** [comment]
Closing this for now.
The proposed solution here is to read WIQL from the file and pass it as param to the wiql query command.

Please reopen this issue, in case this there is a valid scenario which can only be achieved through this
