### ISSUE TITLE
board work item

### ISSUE THREAD

**Issue by gomaltao** [Azure/azure-devops-cli-extension#442]
I am working in a company that uses Azure Devops. As a visually impared user of a screen reader the Devops site is quite difficult to use. I am trying to understand how to use the devops cli extension in stead. I want to get a list of all work item in a board but I don¨t find any command for that.

**Comment by georgevergh** [comment]
@gomaltao  - thank you for reaching out. We are committed to help you succeed using Azure DevOps extension to manage Azure DevOps. Today we support only query by ID to fetch a set of work items. Here is the command reference - https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards?view=azure-cli-latest#ext-azure-devops-az-boards-query

We are working on two commands:
1. Work item query list so that you can quickly fetch the ID and pass it to the query command.
2. Work item search command so that you can run your searches.

ETA - We are still creating the spec and I will publish it as an issue. Rough timeline estimate would be about 2-5 weeks. I will keep you posted on progress.

**Comment by geverghe** [comment]
@gomaltao  - thank you for reaching out. We are committed to help you succeed using Azure DevOps extension to manage Azure DevOps. Today we support only query by ID to fetch a set of work items. Here is the command reference - https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards?view=azure-cli-latest#ext-azure-devops-az-boards-query

We are working on two commands:
1. Work item query list so that you can quickly fetch the ID and pass it to the query command.
2. Work item search command so that you can run your searches.

ETA - We are still creating the spec and I will publish it as an issue. Rough timeline estimate would be about 2-5 weeks. I will keep you posted on progress.

**Comment by gomaltao** [comment]
Thank you for the quick answer. I can't see any information on how to
create the query or what a query is.

/Goaml

**Comment by gomaltao** [comment]
I was to fast. I succeeded to write some query using the work item
query format. Maybe it is a good idea to get some predefined queries.

/Gomal

**Comment by ishitam8** [comment]
@gomaltao , Glad to hear that you were able to figure out query. Sure, we'll add some examples in help text or the documentation for query. Thanks for the feedback!

**Comment by gauravsaralMs** [comment]
@geverghe , @ishitam8 : The requirement here is work item search command? Or something else as well?

cc: @snankani

**Comment by gauravsaralMs** [comment]
@gomaltao : If possible can you please share the scenario which you are trying to solve using Azure DevOps CLI? and what all functionality you will be needing for the same

**Comment by gauravsaralMs** [comment]
@gomaltao : Gentle ping

**Comment by gauravsaralMs** [comment]
closing for now, as we are not clear about the requirement.
please feel free to re-open again or open a new issue with specific requirements
