### ISSUE TITLE
[Feature Request] Azure DevOps CLI Agent Pool parameter

### ISSUE THREAD

**Issue by jclark0909** [Azure/azure-devops-cli-extension#457]
**Is your feature request related to a problem? Please describe.**

I would like to queue build using the Azure DevOps CLI in a different agent pool then the default. We are building out build boxes and would like to test builds in a different que then the default.

**Describe the solution you'd like**

Add a parameter to the Azure DevOps CLI that will allow the user to specify the build que instead of forcing the build to go to the default agent pool.

**Comment by atbagga** [comment]
To be taken care as part of #333.

**Comment by atbagga** [comment]
The API for agent pools is exposed only recently in 5.1 APIs. We DO use it in Pipeline create command which is in preview. 
Using the same in "az pipelines build queue" will be wrong since this command is not in preview and APIs in 5.1 version are subjected to change.  

I initially thought of adding it to "az pipelines run" but in long term it doesn't make sense to add this since yaml pipelines don't use the agent pool from definition settings they use the pools from the yaml definition. 

Considering the above we have the following 3 options - 

Option 1: Use a preview API in build queue command. (Cons: It is prone to break in future.)
Option 2: Use the preview API in pipelines run command since it can pretty much work with old builds too. (Cons: Doesn't make sense for yaml based pipelines)
Option 3: No action. As people move to yaml based pipelines agent pool parameter will become useless. 

For now we will go with 3 and move this to our backlog.

**Comment by atbagga** [comment]
Adding an option to let the user specify the agent pool queue id when queuing a build. 
To support names we will need to upgrade the API version support, since the API is exposed only recently in 5.1.

**Comment by atbagga** [comment]
Fixed in #623. Will be available in the next release (0.9.0) in next week.
