### ISSUE TITLE
Manage security groups

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#471]

**Comment by geverghe** [comment]
Spec against which we are actively developing the security group management commands:

## Security Group Management
| Scenario | Command | Comments |
|--|--|--|
| As an admin, I want to create a security group| `az devops security group create --name --description --project ` | |
| As an admin, I want to update a security group details| `az devops security group create --group-id --name --description --project ` | |
| As an admin, I want to delete a security group| `az devops security group delete --group-id`| |
| As an admin, I want to view all security groups in project | `az devops security group list --project`| |

## Security Group Membership Management
| Scenario | Command | Comments |
|--|--|--|
| I want to add a member to the security group | `az devops security group membership add --member-id --group-id`| |
| I want to add the security group as a member of another group| `az devops security group membership add --member-of-id --group-id`| |
| I want to remove a member from the security group | `az devops security group membership remove --member-id --group-id`||
| I want to remove a the security group as a member of another security group | `az devops security group membership remove --member-of-id --group-id`||
| I want to view all members of the security group | `az devops security group membership list` or `az devops security group membership list --relationship member`|
| I want to view the security groups to which the group belongs to | `az devops security group membership list --relationship memberof` | |

**Comment by Ashu6753** [comment]
Hi geverghe,

By when should we expect this feature to be added to the azure devOps cli? Is there any timeline for this?
Also is there any way we can assign extension to a user account through azure-devops-cli.
Looking forward for your reply. Thanks in advance

**Comment by geverghe** [comment]
Hey @Ashu6753 , thank you for reaching out. We are looking at this coming out around mid of April. I will keep you posted in case there are any change of plans. We haven't factored the extension assignment in user management today. Could you raise a feature request for this? This will help us hear from others with similar needs and help us prioritize.

**Comment by Ashu6753** [comment]
> Hey @Ashu6753 , thank you for reaching out. We are looking at this coming out around mid of April. I will keep you posted in case there are any change of plans. We haven't factored the extension assignment in user management today. Could you raise a feature request for this? This will help us hear from others with similar needs and help us prioritize.

Hi geverghe,

Thanks for the response. I have created feature request #485 for the extension assignment in user management.

Extension Assignment in user management[Feature Request] #485

**Comment by ishitam8** [comment]
Updating all the command structures to use descriptors instead of UID.
VSIDs are not always displayed in all API responses , and converting back and forth betwwen VSID and descriptors could lead to confusion in case for MSA and AAD groups [Since origin ID would differ in this case] 

## Security Group Management
| Scenario | Command | Comments |
|--|--|--|
| As an admin, I want to create a security group| `az devops security group create --name --description --project  groups` |  You can also materialize existing AAD group using this command and use it later to add it to other groups|
| As an admin, I want to update a security group details| `az devops security group update --id --name --description` | |
| As an admin, I want to delete a security group| `az devops security group delete --id`| |
| As an admin, I want to view all security groups in project | `az devops security group list --project`| |

## Security Group Membership Management
| Scenario | Command | Comments |
|--|--|--|
| I want to add a member to the security group | `az devops security group membership add --member-id --group-id`| |
| I want to remove a member from the security group | `az devops security group membership remove --member-id --group-id`||
| I want to view all members of the security group | `az devops security group membership list` or `az devops security group membership list --relationship member`|
| I want to view the security groups to which the group belongs to | `az devops security group membership list --relationship memberof` | |

**Comment by snankani** [comment]
security group commands were released in 0.7.0 release

https://github.com/Azure/azure-devops-cli-extension/releases/tag/20190502.2
