### ISSUE TITLE
Automate configuring authentication to Azure Artifacts feeds

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-devops-cli-extension#540]
**Is your feature request related to a problem? Please describe.**
It is very difficult to automate use of Azure Artifacts NPM packages.  Human users have to periodically download a credentials file with a relatively short lifespan.  More importantly, I have yet to find a way to automate authentication for non-human users using `yarn install`, such as in a build script.

**Describe the solution you'd like**
`az artifacts npm auth --feed <feed> --org <org>` should configure the credential file in the current working directory for the current authenticated user.

`az artifacts npm auth --feed <feed> --org <org> --auto-renew` should configure the credential fille in the current working directory for the current authenticated user and periodically update the credential file to ensure the credential file never expires.

Ideally other package types would support a similar command.  For example: `az artifacts nuget auth ...` would install and configure the [Artifacts Credential Provider](https://github.com/Microsoft/artifacts-credprovider).

**Comment by jlorich** [comment]
I'd like to second this.  The current experience for authenticating with nuget is poor.  Nuget.exe is required for the credential provider but that isn't something used by most people anymore.  VS Integration is good but for anyone using code or other tools the integration is difficult.  Being able to authenticate to Artifacts hosted nuget through the Azure CLI would greatly improve the process.  This would make it easier on build servers as well.

**Comment by zarenner** [comment]
@elbatk and/or @zjrunner to comment here (on Azure CLI integration specifically).

While I'm not sure about integration with Azure CLI, we're certainly investing in improving our auth experience. For npm specifically, we're starting to look at if it makes sense to build tools similar to what you describe / similar to https://github.com/zumwald/better-vsts-npm-auth. I'm sure our PM @elbatk would be very interested to hear your thoughts here.

We also have some other auth-related improvements we've been working on:

- We're currently finishing [new authentication tasks](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) that help set up authentication and "get out of the way" so that you can use the client just as you would locally, instead of having to use specific tasks to do a restore or publish.

- We've added credential provider support for Python (pip, twine) via [artifacts-keyring](https://github.com/Microsoft/artifacts-keyring).

Again, we're very interested in other auth improvements we can make, whether or not they involve Azure CLI.


@jlorich, I want to make sure I understand your concerns - the cross-platform [Azure Artifacts Credential Provider](https://github.com/microsoft/artifacts-credprovider) works not just with nuget.exe and VS but also with dotnet and newer versions of MSBuild (which have NuGet restore functionality built-in). With this credential provider, you can install it on a private build server and get automatic integrated domain auth, as well as configure environment variables if you need it to provide a specific PAT for specific feeds. If you're using Pipelines, the soon-to-be-released NuGetAuthenticate task also uses the credential provider to set up dotnet/nuget/etc to use the build identity.

There's an older credential provider (CredentialProvider.VSS.exe) which does only support nuget.exe, which is possibly what you were referring to? Unfortunately I believe our "Connect to Feed" UI still serves this older credential provider rather than recommending the new one (@jotaylo @pspill), which would explain the confusion.

**Comment by chriskuech** [comment]
What's the benefit of CLI fragmentation and a decentralized solution?

There's no benefit in implementing auth in the language that it's associated with--you can't add the auth package to the package.json/requirements.txt/etc because it is prerequisite to installing all those packages.

**Comment by zarenner** [comment]
If we build auth tooling into the CLI, it's either:
a. only available via the CLI
&nbsp;or
b. a wrapper around other tools / package managers / scripts (or a re-implementation)

If (a), we leave out a number of users that don't want to use the CLI or aren't able to (e.g. can't install python). Requiring npm users to install python, Azure CLI, etc just in order to use us isn't a great experience.

I have no real issue with (b) except that there's a surprising amount of engineering cost to it - at minimum we need to invoke each underlying package manager or script and detect success/failure, bubble up error messages correctly (e.g. if users are missing npm/pip/etc), etc. Is that development and support cost worth it compared to other features, when another auth setup mechanism will already exist? Maybe, maybe not, and I'm sure Elijah will have thoughts here.

> you can't add the auth package to the package.json/requirements.txt/etc because it is prerequisite to installing all those packages.

True. That said, there may still be benefit in implementing auth setup in a way that conforms with the patterns people are already used to in that language for installing tools - e.g. python users are used to `pip install`, node users are used to `npm install -g`, dotnet users may be used to `dotnet tool install`, etc.

**Comment by elbatk** [comment]
This is great discussion. I think authentication via the Azure CLI would be great for the specific flows and users that are using those flows. With that said, a good thing to bring up is that Universal Packages can only be downloaded/uploaded via the Azure CLI, and I get frequent (weeklyish) requests for other ways to be able to get them or push them. 

I don't think that auth in the Azure CLI would be a cure-all for auth, it would be an alternative way for users, and on top of the costs to implement it would increase our support costs. There are a lot of things to consider. If this issue, or a post on the dev community caught a lot of attention, we would be in a good position to consider that work, but for now I think our current improvements to authentication are a good step in the right direction.

**Comment by chriskuech** [comment]
If you are working on a headless and xplat equivalent of vsts-npm-auth, do you have repo I can watch?

**Comment by zarenner** [comment]
@chriskuech nothing currently in development yet, @elbatk can hopefully speak to timeline.
