### ISSUE TITLE
[Feature Request] 'az devops login' should take PAT as a parameter

### ISSUE THREAD

**Issue by hjlarrea** [Azure/azure-devops-cli-extension#704]
**Feature Request**
'az devops login' command should take an additional parameter instead of prompting the user to enter the PAT after executing the login command.

**Proposed Solution**
I'd like to see an optional parameter added to the 'az devops login' command (named `--PAT` and/or `-p`) to allow the user to input the PAT as a parameter instead of requesting it interactively after the user executed the login command. The current approach (interactive input for the token) should be kept as the default behaviour overridden only when the user has defined the `--PAT` option.

**Additional context**
Under some specific scenarios users will require to automate tasks using az devops commands, therefore the login command should be executable without requiring manual intervention (imputing the token).

I do believe that token logins are persistent through sessions, yet some workloads will run under contexts that are not persistent or that would not allow an interactive session to be established to login the very first time using a PAT interactively.

It is true that a PAT should be kept secret and not be exposed. But the current option for automation (echoing the token and piping it into the `az devops login` command) exposes the token as well. The command description should include a brief disclaimer indicating the user should take measures to protect the PAT (depending on the automation mechanism used to execute the task different options might be suitable, like PowerShell secure strings, Ansible Tower credentials, etc.).

**Comment by ishitam8** [comment]
HI @hjlarrea  ,

You can login to azure devops CLI for non-interactive environments in following two ways.
1. Storing your PAT in environment variable.
2. Piping and fetching the PAT from a file.

Refer [login with PAT doc](https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/samples.md#log-in-via-azure-devops-personal-access-token-pat) for more details.

PAT is not accepted as a parameter in `az devops login` command because your commands history is been logged, and if you pass your PAT as a parameter, your PAT gets logged too, which is not advisable.

Feel free to re-open the issue if you have any more questions/suggestions.

**Comment by azurekid** [comment]
What you also can do is store the pattoken of your NPA (non personal account) in an Azure Key Vault
Only give your pipeline SPN access to the Key Vault and fetch the value from your pipeline.

Then pipe the secure variable to login with AZ CLI 
$(pattoken) | az devops login
