### ISSUE TITLE
[Question] Warning when trying to create a pipeline

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#717]
I noticed that it throws a warning in the Component Detection (auto-injected by policy) part.

Here is the warning I’m receiving:
[WARN] Provided search path /home/vsts/work/_tasks/ComponentGovernanceComponentDetection_f2f0881f-4b99-4a1c-80ea-f5b13fd6cec4/0.20710.1/ComponentDetectionTool/Plugins does not exist. 

@squassina - FYI

**Comment by atbagga** [comment]
This is a behavior irrespective of creating a pipeline from CLI or UI. 

The warning is coming from the task itself so as mentioned in the logs please visit http://aka.ms/oss_add_cg_autoinject for point of contact for issues with respect to that specific task.

Closing the issue since it is not CLI specific.
