### ISSUE TITLE
[Bug] version 0.13.0 writes to STDERR breaking build pipelines

### ISSUE THREAD

**Issue by aweiker** [Azure/azure-devops-cli-extension#811]
**Describe the bug**
As of version 0.13.0 of azure-devops a message is written to STDERR for every command that is executed. As a result I had to change all of our build scripts to redirect STDERR to `/dev/null` whenever executing any of these commands. 

For example just 

**To Reproduce**

Azure-Devops extension version: 
```
azure-cli                         2.0.74
command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.13.0
interactive                        0.4.3
```

```
az pipelines list --organization https://dev.azure.com/ME/ --project "TEST" --query "[].{name: name, id: id}"
```
**Expected behavior**
Provide a list of projects with nothing written to STDERR

**Comment by atbagga** [comment]
Thanks for reporting the issue. 

Looks like this is due to the new Preview feature in Azure-CLI which we included in this release to mark the commands as preview. This should be happening only for preview commands.

Will take a look at it on priority.

**Comment by atbagga** [comment]
@aweiker While I am following up with the Knack/Azure-CLI teams for the behavior, it looks correct to me that a preview command sends out a warning that it might change. It is on the author of the script to allow warnings if some one intentionally wants to use the preview functionality. 

Script should fail/pass depending on the exit code rather than stderr. Fail on stderr is more like treat warning as error which you cannot if you are using a preview command in Azure-CLI.

Powershell Task in Azure-Pipelines-

![image](https://user-images.githubusercontent.com/11888714/66297425-48fe9000-e90d-11e9-82b1-bb535796aac6.png)

**Comment by atbagga** [comment]
@aweiker The Knack/Azure-CLI team came back with the same response as I suggested above. I see there are already issues filed there for other commands.

Since this behaviour is consistent with the Azure-CLI framework, I am closing this issue. 

Feel free to follow up here or on Azure-CLI issue if you have some feedback.
