### ISSUE TITLE
az devops login fails w/ ""Failed to unlock the collection!"

### ISSUE THREAD

**Issue by jorkl** [Azure/azure-devops-cli-extension#821]
## Describe the bug

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.13.0.`

**Errors:**
```
Failed to unlock the collection!
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure-devops/keyring/backends/SecretService.py, ln 64, in get_password
    collection = self.get_preferred_collection()
azure-devops/keyring/backends/SecretService.py, ln 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login --organization {} --verbose --debug`

## Environment Summary
```
Linux-4.15.0-62-generic-x86_64-with-debian-buster-

**Comment by jorkl** [comment]
Note: It also fails upon "az repos list" with the very same symptom & error messages.

**Comment by ishitam8** [comment]
Seems like Seahorse/Keyring collection was unintentionally locked for you. 
This usually happens when user has auto login enabled, but has dismissed the keyring prompt or some other app using keyring which has locked the tool.

- Can you try following steps:

   Go to Apps -> Seahorse [Gnome Keyring] 
                               -- Passwords -> Login and/or Default
                                - Unlock this collection if its locked 
                                 [you will need the password which was used by you to set up the keyring for the first time]

You should be able to run “az devops login” command successfully after this.

The first time system uses keyring [ first login of azure-devops in this case ] , gnome keyring prompts user to set up a password for keyring for future uses.  
Once the Seahorse keyring is unlocked, keyring library should  be able to store secrets in Seahorse. 

This could be verified by looking at "Default" passwords in seahorse which would say something like this “Password for Personal Access Token on azdevops-cli: {ORGURL}”  
               OR
You can also check the debug logs for “az devops login’ command.

         keyring.backend : Loading KWallet
         keyring.backend : Loading SecretService
         keyring.backend : Loading Windows
         keyring.backend : Loading chainer
         keyring.backend : Loading macOS
         Keyring backend : keyring.backends.SecretService.Keyring (priority: 5)
         Setting credential: azdevops-cli: default  



- If even after unlocking the collection manually from Seahorse, the issue persists, you can try rebooting the system.
Keyring library might be caching the default keyring backend somewhere.  
Then, try running “az devops login” command, which will prompt you to enter password to unlock the keyring if its locked, and then will store your PAT in Seahorse.
Ideally, seahorse should have popped this prompt first time you were trying to run “az devops login”.

**Comment by geverghe** [comment]
Hey @jorkl - Hope the clarification and guidance solved your issue. I am closing this issue - feel free to reopen in case you are still facing the issue/need more help on this.
