### ISSUE TITLE
Example needed

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-devops-cli-extension#824]
Just linking issue created here:

https://github.com/Azure/azure-cli-extensions/issues/994

**Comment by geverghe** [comment]
Thank you @zikalino for raising the issue here. However, this command is a bit complex and may not be quite clear even with the example. We will work on including the link to [this](https://docs.microsoft.com/en-us/azure/devops/cli/permissions?view=azure-devops) documentation as well. Let me know your thoughts.

**Comment by ishitam8** [comment]
Docs are now updated, thanks
