### ISSUE TITLE
[Bug] "az devops extension install" failing with 500 errors

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#825]
Reference
https://github.com/Azure/azure-cli-extensions/issues/965

**Comment by ishitam8** [comment]
Actually the command works fine with extension ID instead of name. It should be :
`az devops extension install --extension-name "veracode-vsts-build-extension" --publisher-name "Veracode"`

Since , the output of extension search query contains both Extension ID and name, user might get confused as to send name in parameter --extension-name , which would return no results.

![extensionSearch](https://user-images.githubusercontent.com/43136080/67080576-298c2080-f1b3-11e9-99af-df9ab3770793.PNG)

@geverghe  , @gauravsaralMs  ,Can we rename --extension-name to --extension-id and --publisher-name to --publisher-id?
 I know this is inconsistent with API argument names. But the other alternative would be to change search extension table results.

**Comment by geverghe** [comment]
Makes sense. @ishitam8 - including this in the planned lane to ensure this goes in the next release.
