### ISSUE TITLE
[Bug] : [Artifacts] AttributeError: 'module' object has no attribute 'uuid4'

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#828]
Referencing issue from Azure CLI extension repo
https://github.com/Azure/azure-cli-extensions/issues/772

**Comment by activey** [comment]
What is the status of this one? I'm going in a circle between all the other issues referenced! Hello?!

**Comment by idiocache** [comment]
Also impacting RHEL 7.7

**Comment by satbai** [comment]
I was able to reproduce this issue with Python 2.7 and it got fixed by updating Python to 3.6. Please update the version of Python that the az cli uses. As you can see from the [docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#prerequisites), Python version 3.6 or higher is now a prerequisite as the support of 2.7 is getting dropped.
