### ISSUE TITLE
[Feature Request] az devops service-endpoint does not accept secrets

### ISSUE THREAD

**Issue by heoelri** [Azure/azure-devops-cli-extension#917]
**Is your feature request related to a problem? Please describe.**
Currently `az devops service-endpoint ` does only accept certificates using parameter `--azure-rm-service-principal-certificate-path` there's no parameter to configure a service-endpoint in Azure DevOps using a Service Principal with a secret.

**Describe the solution you'd like**
I'd like to have the possibility to create a service endpoint in Azure DevOps not only with a Service Principal with a certificate but also with a secret.

**Comment by atbagga** [comment]
@heoelri Secrets are supported to create an AzureRM service-endpoint. 

Here is a sample command signature -
```
D:\GithubRepos\Work\MS\az_ms_repo\azure-devops-cli-extension> az devops service-endpoint azurerm create --azure-rm-service-principal-id 123 --azure-rm-subscription-id 123 --azure-rm-subscription-name 123 --azure-rm-tenant-id 123 --name 123
Azure RM service principal key:
```

In interactive mode you will be prompted for the secret since in Azure-Devops extension we try to avoid that the user enters any form of secret/password in command prompt which becomes prone to leaks in the Cmd/bash history.

In non interactive mode you can specify it using a ENV variable which is provided in the command help text. 

Refer this documentation for more details - https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops#creating-azure-rm-service-endpoint

**Comment by atbagga** [comment]
Closing as not an issue. If you still feel something is missing feel free to @ mention me to reopen.

**Comment by pwouavre** [comment]
@atbagga 

Hi,

I tested this feature throught an automatism scenario to build a complete az devops project.

I'm using this 2 small line for the service connection creation :
`$env:AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_KEY = $SpnSecret.SecretValueText
az repos create --name $azRepoName --org $organization --project $azProjectName`

The result is an "half" provisionned service connection : The SPN secret is not in the service connection configuration and the connection is not verified.

Am i doing something wrong ?

Thanks for your time !

Br,

Simon

**Comment by HermenOtter** [comment]
@pwouavre I am experiencing the exact same issue, did you manage to solve this?

**Comment by pwouavre** [comment]
Hi @HermenOtter, I'm using a certificate now in order to correctly register a service connection : https://docs.microsoft.com/fr-fr/azure/devops/cli/service-endpoint?view=azure-devops#use-a-client-certificate

Have a nice day!
