### ISSUE TITLE
[Bug] password prompt in knack does not work with CTRL+V in windows 

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-devops-cli-extension#921]
Az devops login password prompt does not work when ctrl+v is used on the prompt. 

https://github.com/microsoft/knack/issues/160

Possible change to make it easy to troubleshoot will be to add token length check.. and if the length is too small than expected (guid length) then warning message to the console indicating this issue. 
And login suggested through right click.

**Comment by geverghe** [comment]
Let's go ahead with the string length check since the *(star) experience is again a framework level change that might take time. There are two things that we need to convey
1. Inform the user that the token has not been entered
2. Address the common scenario which is CNTRL + V

Proposed experience
> az devops login
Token: 

Please provide a PAT token. If you are using CNTRL + V to paste the token, it won't work in command line or powershell - https://github.com/microsoft/knack/issues/160. Use right click or console menu to paste the token.

@atbagga @ishitam8 @mitsha-microsoft for review.

**Comment by atbagga** [comment]
Fixed and released in version - 0.17.0.

Note: This is only a workaround to let the user know if CTRL+V was used on command prompt or powershell on windows. The issue still exists as described in https://github.com/microsoft/knack/issues/160
