### ISSUE TITLE
[Bug] az pipelines run --variables flag doesn't support multiple key/value

### ISSUE THREAD

**Issue by etiennetremel** [Azure/azure-devops-cli-extension#930]
The `--variables` flag from the `az pipelines run` command doesn't support multiple key/value.

The behavior is different from the flag description:

```bash
--variables: Space separated "name=value" pairs for the variables you would like to 
             set.
```

**To Reproduce**
Azure Cli Version: 2.0.78
Azure-Devops extension version: 0.16.0

```bash
$ az pipelines run --name foo --variables "var1=value1 var2=value2"
[...]
"parameters": "{'var1': 'value1 var2=value2'}",
[...]
```

**Expected behavior**
```bash
$ az pipelines run --name foo --variables "var1=value1 var2=value2"
[...]
"parameters": "{'var1': 'value1, 'var2: 'value2'}",
[...]
```

**Comment by atbagga** [comment]
@etiennetremel By providing the double quotes you are making the CLI to read this as one string and hence interpret it as you mentioned. "var1=value1 var2=value2"

As mentioned in the help text you only need to provide the list as space separated. 
e.g. ``` --variables var1=value1 var2=value2```

If your variable contains spaces then `` --variables "var1=value with space" var2=value2```

That should help resolve the issue. There are more pointers on quoting issues [here ](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) for your reference.

**Comment by rgadge** [comment]
This recommended method above did not work, and I also see there is an open issue below:
https://github.com/Azure/azure-cli-extensions/issues/2974

I am trying to pass on a list of variables using the approach and it still fails with the following:
cli.azure.cli.core.azclierror: Could not queue the build because there were validation errors or warnings.
Is there a plan to fix this in upcoming versions of a workaround for my situation?
