### ISSUE TITLE
[Feature Request] az artifacts universal publish: exlude files

### ISSUE THREAD

**Issue by FrancescElies** [Azure/azure-devops-cli-extension#940]
### Issue
When I publish a package via `az artifacts universal publish` I would like to have the option of filtering out certain files.

### Feature
Maybe something like `--exclude <regex>`, e.g.:

    az artifacts universal publish --organization "https://myorg.com/" --feed "myfeed" --name "mypackage" --version 0.0.1  --path . --exclude "*.trash"

Would you find this useful?

**Comment by samuelkoppes** [comment]
Thank you for sharing this feature request. Unfortunately we are unable to take this request at this time due to capacity constraints, but we will continue to monitor customer feedback to see if this topic comes up again. If more customers express interest, we will consider prioritizing this feature.

**Comment by fridrichovsky** [comment]
Good day,
I would also appreciate the ability to exclude some files from the package. If the exclusion allowed the same settings as .artifactignore, it would be best.
