### ISSUE TITLE
Service Endpoints for Management Group connections

### ISSUE THREAD

**Issue by danlister** [Azure/azure-devops-cli-extension#970]
**Is your feature request related to a problem? Please describe.**
I cannot create a new Azure RM Service Endpoint to a Management Group through the Azure DevOps CLI. 

**Describe the solution you'd like**
I would like to see a new command and/or collection of parameters to allow Azure RM Service Endpoints to be created for management groups alongside the existing Service Endpoints connections for Service Principals. For example, something like:

`az devops service-endpoint azurerm create 
    --azure-rm-service-principal-id
    --azure-rm-service-principal-password
    --azure-rm-managementgroup-id
    --azure-rm-managementgroup-name
    --azure-rm-tenant-id
    --name
    [--detect {false, true}]
    [--org]
    [--project]`

**Comment by mitsha-microsoft** [comment]
Hi @danlister , sorry for the delay in response. Since you cannot create Service Endpoints for management groups yet, you can still use the `az devops service-endpoint create` command by specifying a configuration file for the Endpoint, as outlined in this doc [Create Service Endpoints using Configuration File](https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops#create-service-endpoint-using-configuration-file). I am attaching a sample config file that works to create an Azure RM Service Endpoint using this command

```json
{
    "administratorsGroup": null,
    "authorization": {
        "scheme": "ManagedServiceIdentity",
        "parameters": {
            "tenantid": "<tenant-id>"
        }
    },
    "createdBy": null,
    "data": {
        "environment": "AzureCloud",
        "scopeLevel": "ManagementGroup",
        "managementGroupId": "<management-group-id>",
        "managementGroupName": "<management-group-name>"
    },
    "description": "",
    "groupScopeId": null,
    "name": "<Name-of-Service-Connection>",
    "operationStatus": null,
    "readersGroup": null,
    "serviceEndpointProjectReferences": [
        {
            "description": "",
            "name": "<Name-of-Service-Connection>",
            "projectReference": {
                "id": "<Project-ID>",
                "name": "<Project-Name>"
            }
        }
    ],
    "type": "azurerm",
    "url": "https://management.azure.com/",
    "isShared": false,
    "owner": "library"
}
```
Please reply back if there is some other issue
